surname = input('surname: ')
first_name = input('first name: ')
street = input('street: ')
number = input('number: ')
zip_code = input('zip code: ')
city = input('city: ')
print(first_name+' '+surname)
print(street,number)
print(zip_code, city)
